### ISSUE TITLE
KK_Bulge conflicts with PMXExporter

### ISSUE THREAD

**Issue by Benjamoose** [ManlyMarco/KoikatuGameplayMods#14]
Hey there!

Just as a preface, by no means am I blaming this mod, as the PMXExport plugin hasn't been updated in a while, and nobody seems to know who the original author even is (or what the latest version even is).

So that being said, this is the only side I can get in touch with to potentially work around the issue.

Basically, if the PMXExport plugin is active (the plugin that allows you to export your Koikatsu Party model as an .obj), it stops the KK_Bulge plugin from working correctly.

The sliders appear in-game still, but the model goes completely flat/default in that area.

Whereas, if the PMXExport plugin is disabled, KK_Bulge works fine again.

I was hoping this would be a potentially easy fix/workaround your end to enable models to be exported with your adjustments.

Thanks for any input on how feasible this is/a response!

**Comment by ManlyMarco** [comment]
Hello!

Sorry, I don't use nor support PMXExport or other model dump plugins. You'll have to find a solution yourself.

**Comment by Benjamoose** [comment]
Ah, that's a real shame, as the author of that plugin is MIA.

Understandable though. Thanks for the response.

**Comment by Snittern** [comment]
> Ah, that's a real shame, as the author of that plugin is MIA.
> 
> Understandable though. Thanks for the response.

I have created a working version from the disassembly of the DLL with some manual fixing. If someone wants to take a crack at making it work with BoneMod, here it is:
https://github.com/Snittern/KoikatsuPmxExporterReverseEngineered
