### ISSUE TITLE
Koikatu Gameplay Mod v1.4.2 unable to use with Bepinex 5

### ISSUE THREAD

**Issue by Torres84f** [ManlyMarco/KoikatuGameplayMods#15]
Hi there I'm interested in the feature to force raw H even if it causes anger but it seems the mod is out of date.

Could you please update it or maybe I'm wrong and you could point me where your latest version is?

Thanks in advance!

**Comment by ManlyMarco** [comment]
v1.4.2 is very old, use v2.1.1 instead.
