### ISSUE TITLE
AI_Pregnancy v2.5 -- Cannot progress H-scene with Shan/merchant

### ISSUE THREAD

**Issue by The-illoomer** [ManlyMarco/KoikatuGameplayMods#16]
After initiating H activity with Shan, the player is unable to finish, change positions, or exit the scene. Currently poking around the code to see what's up.

Thank you for the port!

EDIT: So far, I've narrowed it down to a nullReferenceExeption at line 207 in PregnancyPlugin.Hooks.cs. The null reference seems to result from the call to DetermineInflationState() in the Houshi_Proc() definition. Commenting the Houshi_Proc() method out and rebuilding the .dll resulted in normal activity with Shan, but likely breaks the inflation feature (which I have not tested).

**Comment by ManlyMarco** [comment]
Most likely it's because she's not a normal NPC, probably will need to get filtered out or handled in a special way.
@thojmr

**Comment by ManlyMarco** [comment]
This should have been fixed in last update, closing.
