### ISSUE TITLE
NightDarkener

### ISSUE THREAD

**Issue by i486** [ManlyMarco/KoikatuGameplayMods#18]
It would be great if this plugin can enabled on all maps.

These are maps that NightDarkener doesn't work on.

1F Hallway, 
Class 1-1
1F Bathroom
Love Hotel
Karaoke
Church
Train
Park
Storage Room
Girl's Room
Beach
Live Stage

**Comment by ManlyMarco** [comment]
This is on purpose since these maps are likely to still have lights on. It could be a setting I guess.

**Comment by i486** [comment]
Hoping for Sunshine version :+1:
