### ISSUE TITLE
KKS_Pregnancy v2.5.4 : Cannot change Hplace went heroine after lactation at FreeH

### ISSUE THREAD

**Issue by Loday94** [ManlyMarco/KoikatuGameplayMods#26]
Dear ManlyMarco,
   I have a gameplay issue about cannot change Hplace went heroine after lactation at FreeH. For example , let the heroine change place from ground to bed. If heroine had lactation , as you click on change Hplace (Left up 2nd button) , than the choose is disappear. only can  stay on there or at the sex position button (right 3 button) change the near Hplace went sex position cannot afford that (I mean like bed sex position change to chair sex position). After my test, I should find the problem log.

This is normal log went I checking after click on change Hplace those choose place at there. (Write this for compare)
```
[Debug  :Modding API] SceneManager.sceneLoaded - HPointMove in Additive mode
[Debug  :Modding API] SceneManager.sceneUnloaded - HPointMove
```
This is the situation at heroine after lactation than click on change Hplace.

```
[Debug  :KK_Pregnancy] Adding particles to heroine: 神代 栞
[Debug  :IllusionFixes] Skipping cleanup because of low memory load (51% RAM, 62% Page file, 6838MB available in PF)
[Debug  :Modding API] SceneManager.sceneLoaded - HPointMove in Additive mode
KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <fb001e01371b4adca20013e0ac763896>:0 
  at (wrapper dynamic-method) AssetBundleManager.DMD<AssetBundleManager::LoadAsset>(string,string,System.Type,string)
  at CommonLib.LoadAsset[T] (System.String assetBundleName, System.String assetName, System.Boolean clone, System.String manifestName, System.Boolean check) [0x00049] in <1b51987d4b874b8bad4c1ba3f736ce31>:0 
  at (wrapper dynamic-method) GlobalMethod.DMD<GlobalMethod::LoadAllFolder>(string,string,System.Collections.Generic.List`1<string>,System.Collections.Generic.HashSet`1<string>)
  at HPointMove+<Start>d__28.MoveNext () [0x001ce] in <1b51987d4b874b8bad4c1ba3f736ce31>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <548b4fa0e7e04f27a1b7580930bfb7dc>:0 
 
(Filename: <fb001e01371b4adca20013e0ac763896> Line: 0)

[Debug  :Modding API] SceneManager.sceneUnloaded - HPointMove
```

Here is the full text log.
[Player.log](https://github.com/ManlyMarco/KoikatuGameplayMods/files/7572217/Player.log)

If you need further information like gameplay record video (use OBS Studio to record), please reply this.

your sincerely
Loday94

**Comment by ManlyMarco** [comment]
Try installing the latest version from here https://www.patreon.com/posts/40713494 and see if the issue persists. It should be fixed in latest release.

**Comment by Loday94** [comment]
I know that but 2.5.4 is the latest version. I have make the gameplay record video, I hope it will let you know that situation.

https://user-images.githubusercontent.com/94705563/142738837-bd697c4b-68ea-44ba-8454-47c27ee5dde4.mp4

.

and this record output log
[Player.log](https://github.com/ManlyMarco/KoikatuGameplayMods/files/7575121/Player.log)

also my mod list

![Mod list1](https://user-images.githubusercontent.com/94705563/142738879-9e73a424-6a0a-4dd1-ad02-fdcee1d4a573.png)

![Mod list2](https://user-images.githubusercontent.com/94705563/142738881-a3352f9d-1961-42e6-b29e-03542a976b5a.png)

Hope can help you investigate the problem.

**Comment by Loday94** [comment]
Also,today(1430;utc+8) I have test 3P part of FreeH , those two heroine also have lactation set. The main heroine also have the problem about cannot change Hplace, but change sex position for 2nd heroine (2nd heroine also has lactation on that time), as I click on change Hplace, those choose have back, unknow reason. If you need 3P gameplay record video, please reply this.

**Comment by Loday94** [comment]
Update 3P: change sex position for 2nd heroine and change back sex position for main heroine, thoose change Hplace choose also have back.

the full text log
[Player.log](https://github.com/ManlyMarco/KoikatuGameplayMods/files/7580042/Player.log)

Ps. closed just click wrong button

**Comment by ManlyMarco** [comment]
Can you test if this build works fine for you?
[KKS_Pregnancy.zip](https://github.com/ManlyMarco/KoikatuGameplayMods/files/7596709/KKS_Pregnancy.zip)

**Comment by Loday94** [comment]
Thank you, This build is work find with me.

the test text log (for report)
[Player.log](https://github.com/ManlyMarco/KoikatuGameplayMods/files/7610346/Player.log)
 
I am looking forward for the future build.
