### ISSUE TITLE
GameplayMods - Possible to add angry conversation after force insert sex?

### ISSUE THREAD

**Issue by HwuSam** [ManlyMarco/KoikatuGameplayMods#29]
As title said.

It's so weird the girl give you compliment conversation after force insert sex and then angry leaving.

**Comment by ManlyMarco** [comment]
The plugin uses whatever is available in the game, and there are no angry H end events that I could have used (the anger mechanic was removed altogether in Sunshine, so even that no longer happens).

**Comment by HwuSam** [comment]
> 

how about the angry event of annoying a normal girl(touching) too much .

Can it use for H end angry event?

**Comment by ManlyMarco** [comment]
Hmm, it's a different kind of event, since it has no text, but maybe. It would need some way of generating text commands on the fly or something.
