### ISSUE TITLE
Koikatu Gameplay Mod Registration Screen

### ISSUE THREAD

**Issue by eluphay** [ManlyMarco/KoikatuGameplayMods#31]
Am not sure if this is normal or not, or is being caused by a conflict or not, but the registration screen, does not seem to have any entries for adding more students above 38, So I can't use the increased students feature of the plugin because of this.

**Comment by ManlyMarco** [comment]
You have to turn it on extra slots in the normal game settings first. You might need to get the AfterSchool expansion to see it.

**Comment by eluphay** [comment]
got afterschool, where is the extra slots option?

**Comment by eluphay** [comment]
Is it the option called... "Maximise class registration" in the standard games options menu?

**Comment by eluphay** [comment]
Maximise class registration, That was indeed the option I wanted, thanks for your help marco, that did it. ;)
