### ISSUE TITLE
Orthographic Camera half screen bug.

### ISSUE THREAD

**Issue by Kirbyarm** [ManlyMarco/KoikatuGameplayMods#33]
The concept of this mod is really neat and has some useful potential and applications, but I'm suffering from a pretty deal breaking bug.

As shown in this image: https://i.imgur.com/yL8uEm7.jpeg

A large portion of the screen is always unrendered. I'm not sure if this is intentional or not but it's definitely not something I can use if there isn't a way to improve it. I play windowed 1440p, and Alt + Enter'ing the screen to fullscreen mode the bug persists. Also persists when transitioning to other areas.

Running Koikatsu After School - CE Ver 6.0.2 - Latest Orthographic Camera release as far as I know.

**Comment by ManlyMarco** [comment]
The camera is too close to the ground so it's clipping. You have to move the camera away from the ground, either by using studio instead or by using the noclip cheat.

**Comment by Kirbyarm** [comment]
Thank you :) I'll look into this noclip cheat solution.

**Comment by ManlyMarco** [comment]
It's in the cheat menu. Closing the issue for now.
