### ISSUE TITLE
[New Crests/Features proposal] KKS_LewdCrestX

### ISSUE THREAD

**Issue by Lebleus** [ManlyMarco/KoikatuGameplayMods#35]
Hello,

Here is a list of new crests that could be added with some gameplay changes in story mode :

- Flattened : Flatten the girl's breasts for the day
- Grown-up: Age-up a girl by altering her assets sizes (Cf. https://github.com/SynchronisedNerdism/KK_AgeProgression, for example or as requirement)
- Busty: Grow girl's breasts a few cups (much more than Lactation crest) without lactation
- Broodmother: (Requires KKS_Pregnancy) Set girl fertility to 100 and set Menstruation schedule to "Always risky"
- Futanari: Turn the girl into a futanari (Don't know if it's even technically possible)

Also, I noticed the mecanism regarding the breedgasm crest that wears off at midnight.
An interesting feature for the story mode could be that crests appear randomly from time to time on girls (with may be a way to detect it ?). Those crests would lasts only for a day

**Comment by Almech-Alfarion** [comment]
"Broodmother: (Requires KKS_Pregnancy) Set girl fertility to 100 and set Menstruation schedule to "Always risky""

If I could offer a slight tweak to this suggestion in the name of adding some dynamism to it: 
- You can already do this through the character editor, so perhaps instead or in addition to maxing out the pregnancy chance, if it would be possible to also change the pregnancy speed for just that character. Say, in the KKS Pregnancy settings you have the speed set to x1 (40 weeks), but a character with the Broodmother crest would have their speed individually changed to x2, x4 or x10, possibly as its own setting in the Lewd Crest Config. 
- Alternatively, have the modifier only kick in when the character is in a Lewd State.

**Comment by Lebleus** [comment]
I think it would be better in addition to maxing out the pregnancy chance. 
I assume the purpose of "crests" in story mode is to "alter/modify" a girl's parameters without doing it in the character editor.

**Comment by ManlyMarco** [comment]
> Flattened : Flatten the girl's breasts for the day

Added as Reduction crest.

> Grown-up: Age-up a girl by altering her assets sizes (Cf. https://github.com/SynchronisedNerdism/KK_AgeProgression, for example or as requirement)

Already kind of exists as Vibrancy crest.

> Busty: Grow girl's breasts a few cups (much more than Lactation crest) without lactation

It would be too similar to the Lactation crest so I'll just increase Lactation crest effect a little.

> Broodmother: (Requires KKS_Pregnancy) Set girl fertility to 100 and set Menstruation schedule to "Always risky"

Added.

> Futanari: Turn the girl into a futanari (Don't know if it's even technically possible)

It would be problematic and require spaghetti code so I'll leave this one out.


Looks like I'm done with all the suggestions from this thread so I'll close it. I'll make a release later today.
