### ISSUE TITLE
Translating descriptions to LewdCrestsX

### ISSUE THREAD

**Issue by Nexurion** [ManlyMarco/KoikatuGameplayMods#43]
Hi! I want to try to translate the description of the crests into other languages. Tell me, please, in which file is the description?

**Comment by ManlyMarco** [comment]
It's inside https://github.com/ManlyMarco/KoikatuGameplayMods/raw/master/src/Core_LewdCrestX/crests
You can use SB3U to open this file and extract the text asset.
To apply the translations you'll have to add them to AutoTranslator, but I'm not sure if it'll work right away or if I'll have to do something extra. You'll have to turn on EnableIMGUI in its config file at least.
