### ISSUE TITLE
"Broodmother" crest doesn't accelerate pregnancies

### ISSUE THREAD

**Issue by DammitDarian** [ManlyMarco/KoikatuGameplayMods#46]
I tried installing and re-installing, but Broodmother only seems to guarantee pregnancy, it doesn't appear to cause pregnancies to progress any faster than the rate dictated in Pregnancy 2.7

**Comment by DammitDarian** [comment]
> 

Apologies, I may not have been clear enough...when I mentioned that it doesn't appear to cause pregnancies to progress any faster than the rate dictated in Pregnancy 2.7, I wasn't just saying that it didn't progress daily. When Preg is set to 10, the pregnancy increases by 10. When Preg is set to 4, pregnancy increases by 4 during weekly progression.

The crest doesn't seem to change the rate in any way, not even though weekly progression.

As an aside, it would be nice if you brought breedgasm back...seeing the belly change throughout the day was nice.

**Comment by ManlyMarco** [comment]
Which game and game version?

**Comment by DammitDarian** [comment]
> Which game and game version?

Koikatsu Sunshine. Not sure what you mean by which version, but I'm using the updater.

**Comment by ManlyMarco** [comment]
I've just tested and with latest version of KKSAPI, Pregnancy and LewdCrestX the Broodmother crest works correctly. It just takes long for the changes to appear because you have to skip 7 days for one step, and another 7 for the second step.

**Comment by ManlyMarco** [comment]
Latest release updates the progress daily and should show the crest effect much better. https://github.com/ManlyMarco/KoikatuGameplayMods/releases/tag/p2.7.1
